// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1yIuvCuplOsaPgRXSCcjOz2z3ful5AeM',
    appId: '1:293568464040:web:610554596a3803acfd2e9d',
    messagingSenderId: '293568464040',
    projectId: 'guardian-os-80042',
    authDomain: 'guardian-os-80042.firebaseapp.com',
    storageBucket: 'guardian-os-80042.firebasestorage.app',
    measurementId: 'G-SSL4N42HG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGApwIGZ1UVQY5Vpdv44QHOwpOrXLogqM',
    appId: '1:293568464040:android:dbf94be6003a6ccafd2e9d',
    messagingSenderId: '293568464040',
    projectId: 'guardian-os-80042',
    storageBucket: 'guardian-os-80042.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPXCf8Q4v3iAkUKlv7ArCwk8cH4ekozkk',
    appId: '1:293568464040:ios:27cd3791520fb545fd2e9d',
    messagingSenderId: '293568464040',
    projectId: 'guardian-os-80042',
    storageBucket: 'guardian-os-80042.firebasestorage.app',
    iosBundleId: 'com.cyberwarriors.guardianSos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPXCf8Q4v3iAkUKlv7ArCwk8cH4ekozkk',
    appId: '1:293568464040:ios:27cd3791520fb545fd2e9d',
    messagingSenderId: '293568464040',
    projectId: 'guardian-os-80042',
    storageBucket: 'guardian-os-80042.firebasestorage.app',
    iosBundleId: 'com.cyberwarriors.guardianSos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1yIuvCuplOsaPgRXSCcjOz2z3ful5AeM',
    appId: '1:293568464040:web:9c3cf29735483af0fd2e9d',
    messagingSenderId: '293568464040',
    projectId: 'guardian-os-80042',
    authDomain: 'guardian-os-80042.firebaseapp.com',
    storageBucket: 'guardian-os-80042.firebasestorage.app',
    measurementId: 'G-S9Q7DCLGYM',
  );
}
